name: Run Tests and Coverage

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.4'
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Set environment to test
        run: echo "RAILS_ENV=test" >> $GITHUB_ENV

      - name: Prepare Test DB
        run: bundle exec rake db:test:prepare

      - name: Run migrations on Test DB
        run: RAILS_ENV=test rails db:migrate
        
      - name: Seed Test DB
        run: RAILS_ENV=test rails db:seed

      - name: Run RSpec tests
        run: bundle exec rspec

      - name: Run Cucumber tests
        run: bundle exec cucumber

      - name: Check Code Coverage
        run: |
          value=$(jq -r '.result.line' coverage/.last_run.json);
          if (( $(echo "$value < 90" | bc -l) )); then
            echo "::warning::Coverage is less than 90: $value"
          fi
        
